#define CONNECTION_ERROR 1
#define FAILED_READ_TEMP 2

#define HEARTBEAT_IN_MS 120000

#define SYSTEM_STATE_OFF 1
#define SYSTEM_STATE_MAINTENANCE 2

#define ARDUINO_NOT_REACHABLE_ERROR 1
#define DATA_TO_OLD_DIF 3660000

#define TEMP_UNABLE_HIGH 55.0
#define TEMP_UNABLE_LOW -20.0
