

#define HEARTBEAT_IN_MS 120000

#define SYSTEM_STATE_OFF 1
#define SYSTEM_STATE_MAINTENANCE 2

#define NO_ERRORS_STATE 0
#define FAILED_READ_SENSOR 1
#define FAILED_SET_TEMP 2
#define FAILED_CONNECTING_TO_WIFI 4
#define FAILED_CONNECTING_TO_FIREBASE 5

#define TEMP_UNABLE_HIGH 55.0
#define TEMP_UNABLE_LOW -20.0
