#define HEARTBEAT_IN_MS 120000

#define SYSTEM_STATE_OFF 1
#define SYSTEM_STATE_MAINTENANCE 2

#define NO_ERRORS_STATE 0
#define FAILED_READ_TEMP 1
#define TEMP_DATA_OUTDATED 2
#define FAILED_CONNECTING_TO_WIFI 4
#define FAILED_CONNECTING_TO_FIREBASE 5

#define DATA_TO_OLD_DIF 3660000
