#define HEARTBEAT_IN_MS 120000

#define SYSTEM_STATE_NO_ERRORS 0
#define SYSTEM_STATE_OFF 1
#define SYSTEM_STATE_MAINTENANCE 2

// ArduinoPump states which are sent to server.
#define NO_ERRORS_STATE 0
#define FAILED_READ_TEMP 1
#define TEMP_DATA_OUTDATED 2
#define FAILED_READ_SYSTEM_STATE 3

// Count of LED Blinking when running in these issues.
#define FAILED_CONNECTING_TO_WIFI_LED_COUNT 3
#define FAILED_CONNECTING_TO_FIREBASE_LED_COUNT 5

#define CONNECT_WIFI_TRYS_MAX 5
#define READ_SYSTEM_STATE_TRYS_MAX 5
#define RESET_FIREBASE_TRYS_MAX 5

#define CONTROL_MODE_AUTOMATIC 0
#define CONTROL_MODE_ALWAYS_ON 1
#define CONTROL_MODE_ALWAYS_OFF 2

#define DATA_TO_OLD_DIF 3660000
